# -*- coding: utf-8 -*-
"""PRODIGY_CS_01 (SUSHMA T A)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CVgkADvay_DJd583NjsUKukGK4sBdfPE
"""

def caesar_cipher(text, shift, mode):
    result = ""
    for char in text:
        if char.isalpha():
            shift_amount = shift % 26
            if mode == 'encrypt':
                if char.islower():
                    result += chr((ord(char) - ord('a') + shift_amount) % 26 + ord('a'))
                else:
                    result += chr((ord(char) - ord('A') + shift_amount) % 26 + ord('A'))
            elif mode == 'decrypt':
                if char.islower():
                    result += chr((ord(char) - ord('a') - shift_amount) % 26 + ord('a'))
                else:
                    result += chr((ord(char) - ord('A') - shift_amount) % 26 + ord('A'))
        else:
            result += char
    return result

def main():
    message = input("Enter the message to encrypt/decrypt: ")
    shift = int(input("Enter the shift value (a number between 0 and 25): "))
    mode = input("Enter 'encrypt' for encryption or 'decrypt' for decryption: ")

    if mode.lower() == 'encrypt' or mode.lower() == 'decrypt':
        result = caesar_cipher(message, shift, mode.lower())
        print(f"Result: {result}")
    else:
        print("Invalid mode. Please enter 'encrypt' or 'decrypt'.")

if __name__ == "__main__":
    main()